# Generated by Django 5.2.9 on 2026-07-22 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('uploaded', 'Uploaded'), ('generated', 'Generated')], max_length=10)),
                ('doc_type', models.CharField(choices=[('mri', 'MRI'), ('ct', 'CT Scan'), ('lab', 'Lab Report'), ('prescription', 'Prescription'), ('report', 'Generated Report'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='patient_docs/%Y/%m/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('de_identified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='visits.visit')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('summary', 'Summary'), ('trend', 'Trend Analysis'), ('risk', 'Risk Assessment'), ('generated_report', 'Generated Report Content')], default='summary', max_length=20)),
                ('prompt_used', models.TextField(blank=True)),
                ('llm_response_json', models.JSONField(blank=True, default=dict)),
                ('rendered_html', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='generated_reports/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='documents.document')),
            ],
            options={
                'verbose_name_plural': 'Document analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('embedding_id', models.CharField(help_text='Pointer into the external vector store', max_length=255)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'ordering': ['chunk_index'],
            },
        ),
    ]
