# Generated by Django 6.0.7 on 2026-08-17 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chunk_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, help_text='Source page number in the original PDF', null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Denormalized from document.patient for vector store queries', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='section',
            field=models.CharField(blank=True, default='', help_text='Clinical section heading (e.g. Laboratory Results)', max_length=255),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding_id',
            field=models.CharField(blank=True, help_text='Pointer into the external vector store', max_length=255),
        ),
    ]
