# Generated by Django 6.0.7 on 2026-08-17 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_doctor_id'),
        ('documents', '0003_documentchunk_embedding'),
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedClinicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('consultation_summary', 'Visit / Consultation Summary'), ('prescription', 'Prescription'), ('medical_certificate', 'Medical Certificate'), ('referral_letter', 'Referral Letter')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('form_data', models.JSONField(blank=True, default=dict, help_text='Extra form fields supplied by the doctor (medications, diagnosis, specialist, etc.)')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='clinical_docs/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_clinical_documents', to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_documents', to='patients.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_documents', to='visits.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
